### ISSUE TITLE
Issue without password

### ISSUE THREAD

**Issue by KajuKaVyapari** [AlphaNecron/lightdm-gab-nord#1]
The greeter automatically loads when a user has no password. I want it to wait for me to manually click the 'Login' button before loading.

**Comment by AlphaNecron** [comment]
Try disabling auto login, password is required for users.

**Comment by AlphaNecron** [comment]
This is LightDM's issue, not theme's issue i think.

**Comment by AlphaNecron** [comment]
Closed.
