### ISSUE TITLE
No profile picture during login

### ISSUE THREAD

**Issue by shakakibara12** [AlphaNecron/lightdm-gab-nord#2]
I had the same issue with https://github.com/GabrielTenma/lightdm-gab-gradient.

I posted the same issue there as well
here is the link:
https://github.com/GabrielTenma/lightdm-gab-gradient/issues/7

How can I fix this?

**Comment by AlphaNecron** [comment]
Did you set the profile picture?

**Comment by AlphaNecron** [comment]
You can try following below answer.
[Set LightDM user picture](https://unix.stackexchange.com/a/122177)

**Comment by shakakibara12** [comment]
yes setting the profile picture in `/var/lib/AccountsService/users/<username>` did the trick
Here is the method, if someone is having the same issue
https://wiki.archlinux.org/title/LightDM#Changing_your_avatar
